var searchData=
[
  ['edit_42',['Edit',['../class_family_net_1_1_controllers_1_1_charity_makers_controller.html#a01ac2659f1c7266f817a65f3539c4f70',1,'FamilyNet.Controllers.CharityMakersController.Edit(int? id)'],['../class_family_net_1_1_controllers_1_1_charity_makers_controller.html#accdcc7a0f7217531590346ea5a88df3b',1,'FamilyNet.Controllers.CharityMakersController.Edit(int id, [Bind(&quot;ID,FullName,Address,Birthday,Contacts,Rating&quot;)] CharityMaker charityMaker)'],['../class_family_net_1_1_controllers_1_1_orphanages_controller.html#a3d5b82b22a4c7b5509907afa325e3dba',1,'FamilyNet.Controllers.OrphanagesController.Edit(int? id)'],['../class_family_net_1_1_controllers_1_1_orphanages_controller.html#abb4bf7ab6cb48db7725d21e1fd73979d',1,'FamilyNet.Controllers.OrphanagesController.Edit([Bind(&quot;ID,Name,Adress,Rating,Avatar&quot;)] Orphanage orphanage, int id, IFormFile file)'],['../class_family_net_1_1_controllers_1_1_orphans_controller.html#a0d3f731a3aee7821e61d03bb91b8d269',1,'FamilyNet.Controllers.OrphansController.Edit(int? id)'],['../class_family_net_1_1_controllers_1_1_orphans_controller.html#ac47c5f34de57d9cba7a4b1ff81137b9a',1,'FamilyNet.Controllers.OrphansController.Edit(int id, [Bind(&quot;ID,FullName,Birthday,Orphanage,Avatar&quot;)] Orphan orphan, int idOrphanage, IFormFile file)'],['../class_family_net_1_1_controllers_1_1_volunteers_controller.html#aa9c37ca7a22f042566c29cb8acf06f22',1,'FamilyNet.Controllers.VolunteersController.Edit(int? id)'],['../class_family_net_1_1_controllers_1_1_volunteers_controller.html#a9e406afa3475c8b5d82dfb3d9889050e',1,'FamilyNet.Controllers.VolunteersController.Edit(int id, [Bind(&quot;ID, FullName, Address, Birthday, Contacts, Rating&quot;)] Volunteer volunteer)']]],
  ['editdonation_43',['EditDonation',['../class_family_net_1_1_controllers_1_1_donations_controller.html#a42c042551dbded4d1321ad9d1190c949',1,'FamilyNet.Controllers.DonationsController.EditDonation(int? id)'],['../class_family_net_1_1_controllers_1_1_donations_controller.html#a52f7674208a1c5877b0aa8959f7fd06f',1,'FamilyNet.Controllers.DonationsController.EditDonation(int id, [Bind(&quot;ID,DonationItem&quot;)] Donation donation)']]],
  ['editviewmodel_44',['EditViewModel',['../class_family_net_1_1_models_1_1_view_models_1_1_edit_view_model.html',1,'FamilyNet::Models::ViewModels']]],
  ['efrepositoryasync_45',['EFRepositoryAsync',['../class_family_net_1_1_models_1_1_entity_framework_1_1_e_f_repository_async.html',1,'FamilyNet::Models::EntityFramework']]],
  ['efrepositoryasync_3c_20orphanage_20_3e_46',['EFRepositoryAsync&lt; Orphanage &gt;',['../class_family_net_1_1_models_1_1_entity_framework_1_1_e_f_repository_async.html',1,'FamilyNet::Models::EntityFramework']]],
  ['efunitofworkasync_47',['EFUnitOfWorkAsync',['../class_family_net_1_1_models_1_1_entity_framework_1_1_e_f_unit_of_work_async.html',1,'FamilyNet::Models::EntityFramework']]],
  ['emailservice_48',['EmailService',['../class_family_net_1_1_models_1_1_identity_1_1_email_service.html',1,'FamilyNet::Models::Identity']]],
  ['errorviewmodel_49',['ErrorViewModel',['../class_family_net_1_1_models_1_1_error_view_model.html',1,'FamilyNet::Models']]]
];
