// <auto-generated />
using System;
using FamilyNetLogs.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FamilyNetLogs.Migrations
{
    [DbContext(typeof(FamilyNetLogsContext))]
    partial class FamilyNetLogsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FamilyNetLogs.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CallSite")
                        .HasMaxLength(256);

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("Info")
                        .HasMaxLength(256);

                    b.Property<string>("JSON")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasMaxLength(256);

                    b.Property<DateTime>("Logged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Logger")
                        .HasMaxLength(256);

                    b.Property<string>("Status")
                        .HasMaxLength(50);

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Log");
                });
#pragma warning restore 612, 618
        }
    }
}
